"""
680. 验证回文字符串 Ⅱ

给定一个非空字符串 s，最多删除一个字符。判断是否能成为回文字符串。

示例 1:
输入: "aba"
输出: True

示例 2:
输入: "abca"
输出: True
解释: 你可以删除c字符。

注意:
字符串只包含从 a-z 的小写字母。字符串的最大长度是50000。
"""


class Solution:
    def validPalindromeA(self, s):
        """
        :type s: str
        :rtype: bool
        """
        if (s == s[::-1]):
            return True

        s_len = len(s)

        for i in range(s_len):
            new_s = s[0:i] + s[i + 1:]
            if (new_s == new_s[::-1]):
                return True
        return False

    def validPalindrome(self, s):
        def validPalindrome_a(s, l, r):
            while (l < r):
                if (s[l] != s[r]):
                    return False
                else:
                    l = l + 1
                    r = r - 1
            return True

        left, right = 0, len(s) - 1
        while (left < right):
            if (s[left] != s[right]):
                return (validPalindrome_a(s, left, right - 1)
                        or validPalindrome_a(s, left + 1, right))
            else:
                left = left + 1
                right = right - 1
        return True


s = Solution()
print(s.validPalindrome('aba'))
# print(s.validPalindrome('abca'))
print(
    s.validPalindrome(
        "abvfebncxjfhhzehnaajrqbmgslbeqtlklowshsckuvxbpiukgiagzxnbhmskkzhimoilumduyabqprvwjwralatcvnvqndysdxdjpnjbaecpncoqfkkzxxjzjetpbjkjjhtrxaeodnwaaywysvlrroxkmltgftggcvuaurgnwguqjllzdpmdiopkbdmlmpbazlsawoectmwhflsszzhbtkmlzwcgkeczxejrppdlrwoftshsewplmssnlztlnlzvgezyjgkdlpdgrblghasgxkfufdrqehcgiyodbklkfqwszehfksiamnqovjfcegmkcievflaxribgnqpurybhuvqjyfgzgiripmbwbwhfhkfthmepwyojlgmegjwseagwmizchjnrgigspuzxglaihhneroeoocbawsvyqxnqqrzhonotoyixfjufgnuormwrogalouthxtzvflnbsmtkuyuyoyxuyifmotajcisorvxzqfvkfnhlpxvpogxsfiirsckwnpyzaqkmsgkfiswvvmqkonakkmatymscyihgqsckzqepatetzjvvkdlsyyilqjnipocomjucoslxqbwohqxdqtaajugwalwsqpkzakcxwzrdwdxzedazlqnnnuzldvdobggykbzgpbaejzwgaiahdpuesrplchpwjhlgowqvhyrjejxhlirofaqcccvewqkgaxxfcckvfpqlkiqlduqgxexmyvqoharkvbesgjbqpmcphsqlvbzlljnpbawjgpifbzrmkvqixveigocgnkkidbbfcmlboltvxxtmswfezizgvliedekxwoncqmbxyfjqshwhaekqmwpivoohjtrcctqvlwjddcmjqkelljnljskvwbispudpjalsebjllkmcnakzqxrlwqqtvbeablhtauhdfidqkkwnvsatiububmeytumpkiilhxgfoynkgspkesszjaumdggzlmgdeuhffnfypdhhpfzuxjofcimgzsqowjupgtqsmqlygbylqnktjhrjdxnmqdlpsncgvyzcytearkkloefxcjgzjrhpudnpyjuugaayificgxmeuovdezyhalkukkunadwriznynopxqikqpukhigbyvbxalbldjnzdkrfexuhaztzuzjrcdtpqujqwtwffcdtkaotyrpnwbezwalwtwpdcrihgvxjtfyhskkpoeqmqinzqwnrzcoghxkvncyyhziuqggtdthldbhekgvaauuvydszleizxahaipvmhdphfhuprvlbwhnrusgslmpijhaivpewepotytbmjkyjlsejovcbjqipzyagadbjrtfhojsmnmtflgybptcesefbrvzvyfohsyyzdcjluwhmjhovgxzptakoatzmtgvdybaznyyzuuarvifijgbpezpxesvohghakqlbeshtmaiakawscnlmdtjrlpfgdtpphbxblxmbzstnkdxzsdsklbdwupepzqtajtahvcwgrtdhzjajqeruaqorpmqajdjbtlwrdesafiwibaokxiimbogbyagnzluywemjratqqahzcygzsqmqygjsfhgylovjyxjazpahcocfyqiciwwilnxbalpjyktqdfgwxdbhdximrxgjgzijercbvtunojfbjmveqzyzgmmnxwsmcuybshwmnobkovccvkeiyagmwgchqoxzywfbzxejbgwethzlwminmwyklubolmtkqtsjqvnanztulascmwvwbvfsaudcincvklcxannkphuzvuktbpxmarspymwxwmewohqmjljccrzbloabnfkmoxdjbcbjvmqzwfsozdbhgrxqsuktkmqpfwbvtfxjthhbhebgqpwkdoydzoadudqrlpzwqpifdumqdkggrngvctjwaxjuwqfsdvxsexcpmwcacrmbhqwhrnjfkqsyzcynskrpfkpnavltwrkwqicxmtbilkrwczeyztyaytfysdmdzjlzktmupjzxaqcagtxshfvlfcqtbtznvtgnwwfjjdvjsgqinnzelvjksdazskjlrantdxzozduqcizycecpzafmcvvszwzkzxtxmfspdtnrkdgmhltifnalxqplmeotxmgiblcuukzftpmmwhonfrxhrrrvdidwfvpdhqazioidorizrqueqcdktocgtrykspovuskryiehormclwiwzfcqkxzuobxgflyuvcgyghgqrfrmabtrvacmtosfrdcpexkpkvoqzrofluynniokvbuhdhligtcbvetbollxubkktuefnjwifwdscppbypglztjgltbarnbxocdinysotpyzjmrwgnowjckjelzugryumjfjzfrvocqhnrtluqqbfitqvgniouunbnvuxgmhpbezhfovsjvylwgxiqqqshzksipetsagjtawyhoodivajqklrcmpmobridrhizakbrqgpwfbvyvpchlcpzskkfsdurfrndphlpwowjvxydjokzfqbumhxwtubchtnxchfxfjcoerpcamjspanacvgqerkxfqawwjearzdgundesszfgcfygulrtlohnmmdkeeffyjcgseqaxromwpljfcwtcgaowugewanlslkktrhaziysdiaenucpuiqmczvpayrlbzjypjkseuaanakhqsmvccamwhainyctakyhqdwbmkwhhyqnrrqrdyvldufakxndxsaiedkqdfyeejxuudxmwyxwlkqfosfddqgsyhthtotalzytemgxtzjpaiddftnxcloyzsntbdpvhvcaqddffjedipinzoofrpxknaqnzvjmrzdvhedyofrsqgauvlxzyyrosaxkeqbwsqsyctqjmpxhlmbxzfdapveiblocqgizbhhoxshioaoukdhxmilgnmulhytpzoeisatihjhyiyhfldcghurdbpwjpydwoyenszhfdfiisjesflhbpenwxprktnhmwychrgfpisinplsmteaffxyjsknzencwrvltyfbedkgczvmlnwcpavhdulnebftqrnfupnmqpdnfwvsrlpcxancfxmpnmxejqopqbhpmstgxynhlirugktdhdzxdxanjpchymucjbazpwndsjqrxjambzekbqknkypbrbrvfamfkmyhqdoemrbezunjjmedlyasjjcelsgosftysmkskqopzgnvwgretjdsocsvqjylvafiejgtbjexcyzkkngkeqdehqlanfokusghtydvptgkfqgwkcqutavcmcxlbkfpadlfzgakpslolqbrzuxwbgzxvdulhczwotezxbwwmqejwrvlpugxowbztgtocyoqnnubvvtopjlkcduvqixtxojoypjblalwcgwqbrpimbxzyaaqxcunbpayqrpjzyibtrhudegnlolsfqdaxcftbozpchuaxfyztdnojatlnsfogiajrkxxqolsfpfejwtjblbrnzvgllobenlnwflespyxgbuconmvwdxnvhqeiwvzqytokhuzrposqrqrwytyqojaitbvtzudtkjfkfxkygouaohuzyhqwivmrmbaobkxhdnrkkxawsxlxgazfjjkbnkelgfowgbdoapslfwljhkbwwzrgzixoelqvbpegshqnrjptuoflplwnxjsnuawpoalerswfbjzderduojendmazwuibhvsqjrievmvddcqqgcnmznazwdihdbaudipmtbspmyrofgkprezthhbyprkmsaoiwjqiejexpfrnswndwjnilvgpdtqdlkjcxzilbtqvchzzyzqrukdedoqouongjmfdconplilkdfgvcgdhcjluwhkxcfvmydhvrrzsluwyzkfhiiyyfiaqqnglbmzdrvpxxybhzjiltbcqrjaswlflptdmswzezrumsxeugmcaifdrmhecvrruhziippwvlvfmmalwmalwwnvzgqcnlyveqpkagwfqxfncawsckenuvhyioixjsclzxaiymfklhzbtnatqzkinanpeawrihpbrlvtytgaepxtwjqtiyciwsqeuniywsfgzwbusepejspknqfpfxcomggoqispsdalswgfrdamqwkyzaeyexrdcmgwasojbldbhldlhwsdxyjqzicizovwlgtwclzopyctasvcuklcraisuzqkfuhqyhzxdzdtzdtavqsbqqdlfloafssvgsajsgbnztqcobnuzivhkniuglnmauhgfcjwxmxvknqhghpkrhcvjfwwrawpfagyqtmeitowoeyagqiwosfqsnhwsdvlbmzgasplcnvtdrszzrgsrsmazqpisybfjplnlvhcuaelqimadheinemjspdoacwqntbrvyhbkwdkctxdkxdjivhpcxgxjufirxjsaywysaccquwouwyroskxthknoctwkbqsktqcgqfefisktbtsggnqiqodgvynfxpcgxbgmmjwnivkjxlpvcvayugmstqdasjtsxfvjpiuuacubrcjkinehxjrshzcepeokxvzzkkafofzqvuguvpmxhquxfxhfanwgbuszyvgmkyflshrzwozneecmaspuybapdxurassxyoctpdnxoixrdmlbvraajwfezwdlntqepeardryiycgwegbcylplnlixmckgfnkdrmbseqdgbulzthhcxbnwlwcvcywnwnebannpwmxzywlsaqtppvhpfuxkrgmgjmbmkyxeaqqsyememydjbntuuiosopgmwxlzlhavebfpnwxuxbuxeswphiteokhtsjdzvibkbsmyehwyerttygwhizycimvrdcbzodiqitsmahnflvybkwrdqivnuglwfxmeqqclnuzugrjlvjpirwufenrlmuwykucariilanbskkrihcxyavqkwxejuuykmmyubjhuigbifjjdotuhvsourkrygsjfinjtjcdcoltwdvpxcvudtpdimkkiwllbbqrnpxussszmbvhettehvbmzsssuxpnrqbbllwikkmidptduvcxpvdwtlocdcjtjnifjsgyrkruosvhutodjjfibgiuhjbuymmkyuujexwkqvayxchirkksbnaliiracukywumlrnefuwripjvljrguzunlcqqemxfwlgunviqdrwkbyvlfnhamstiqidozbcdrvmicyzihwgyttreywheymsbkbivzdjsthkoetihpwsexubxuxwnpfbevahlzlxwmgposoiuutnbjdymemeysqqaexykmbmjgmgrkxufphvpptqaslwyzxmwpnnabenwnwycvcwlwnbxchhtzlubgdqesbmrdknfgkcmxilnlplycbgewgcyiyrdraepeqtnldwzefwjaarvblmdrxioxndptcoyxssaruxdpabyupsamceenzowzrhslfykmgvyzsubgwnafhxfxuqhxmpvuguvqzfofakkzzvxkoepeczhsrjxhenikjcrbucauuipjvfxstjsadqtsmguyavcvplxjkvinwjmmgbxgcpxfnyvgdoqiqnggstbtksifefqgcqtksqbkwtconkhtxksorywuowuqccasywyasjxrifujxgxcphvijdxkdxtckdwkbhyvrbtnqwcaodpsjmeniehdamiqleauchvlnlpjfbysipqzamsrsgrzzsrdtvnclpsagzmblvdswhnsqfsowiqgayeowotiemtqygafpwarwwfjvchrkphghqnkvxmxwjcfghuamnlguinkhvizunbocqtznbgsjasgvssfaolfldqqbsqvatdztdzdxzhyqhufkqzusiarclkucvsatcypozlcwtglwvozicizqjyxdswhldlhbdlbjosawgmcdrxeyeazykwqmadrfgwsladspsiqoggmocxfpfqnkpsjepesubwzgfswyinueqswicyitqjwtxpeagtytvlrbphirwaepnanikzqtantbzhlkfmyiaxzlcsjxioiyhvunekcswacnfxqfwgakpqevylncqgzvnwwlamwlammfvlvwppiizhurrvcehmrdfiacmguexsmurzezwsmdtplflwsajrqcbtlijzhbyxxpvrdzmblgnqqaifyyiihfkzywulszrrvhdymvfcxkhwuljchdgcvgfdklilpnocdfmjgnouoqodedkurqzyzzhcvqtblizxcjkldqtdpgvlinjwdnwsnrfpxejeiqjwioasmkrpybhhtzerpkgforympsbtmpiduabdhidwzanzmncgqqcddvmveirjqsvhbiuwzamdnejoudredzjbfwsrelaopwaunsjxnwlplfoutpjrnqhsgepbvqleoxizgrzwwbkhjlwflspaodbgwofgleknbkjjfzagxlxswaxkkrndhxkboabmrmviwqhyzuhoauogykxfkfjktduztvbtiajoqytywrqrqsoprzuhkotyqzvwieqhvnxdwvmnocubgxypselfwnlnebollgvznrblbjtwjefpfsloqxxkrjaigofsnltajondtzyfxauhcpzobtfcxadqfslolngeduhrtbiyzjprqyapbnucxqaayzxbmiprbqwgcwlalbjpyojoxtxiqvudckljpotvvbunnqoycotgtzbwoxguplvrwjeqmwwbxzetowzchludvxzgbwxuzrbqlolspkagzfldapfkblxcmcvatuqckwgqfkgtpvdythgsukofnalqhedqekgnkkzycxejbtgjeifavlyjqvscosdjtergwvngzpoqkskmsytfsogslecjjsayldemjjnuzebrmeodqhymkfmafvrbrbpyknkqbkezbmajxrqjsdnwpzabjcumyhcpjnaxdxzdhdtkgurilhnyxgtsmphbqpoqjexmnpmxfcnaxcplrsvwfndpqmnpufnrqtfbenludhvapcwnlmvzcgkdebfytlvrwcneznksjyxffaetmslpnisipfgrhcywmhntkrpxwnepbhlfsejsiifdfhzsneyowdypjwpbdruhgcdlfhyiyhjhitasieozptyhlumnglimxhdkuoaoihsxohhbzigqcolbievpadfzxbmlhxpmjqtcysqswbqekxasoryyzxlvuagqsrfoydehvdzrmjvznqankxprfooznipidejffddqacvhvpdbtnszyolcxntfddiapjztxgmetyzlatoththysgqddfsofqklwxywmxduuxjeeyfdqkdeiasxdnxkafudlvydrqrrnqyhhwkmbwdqhykatcyniahwmaccvmsqhkanaaueskjpyjzblryapvzcmqiupcuneaidsyizahrtkklslnaweguwoagctwcfjlpwmorxaqesgcjyffeekdmmnholtrlugyfcgfzssednugdzraejwwaqfxkreqgvcanapsjmacpreocjfxfhcxnthcbutwxhmubqfzkojdyxvjwowplhpdnrfrudsfkkszpclhcpvyvbfwpgqrbkazihrdirbompmcrlkqjavidoohywatjgastepiskzhsqqqixgwlyvjsvofhzebphmgxuvnbnuuoingvqtifbqqultrnhqcovrfzjfjmuyrguzlejkcjwongwrmjzyptosynidcoxbnrabtlgjtzlgpybppcsdwfiwjnfeutkkbuxllobtevbctgilhdhubvkoinnyulforzqovkpkxepcdrfsotmcavrtbamrfrqghgygcvuylfgxbouzxkqcfzwiwlcmroheiyrksuvopskyrtgcotkdcqeuqrzirodioizaqhdpvfwdidvrrrhxrfnohwmmptfzkuuclbigmxtoemlpqxlanfitlhmgdkrntdpsfmxtxzkzwzsvvcmfazpcecyzicqudzozxdtnarljkszadskjvleznniqgsjvdjjfwwngtvnztbtqcflvfhsxtgacqaxzjpumtkzljzdmdsyftyaytzyezcwrklibtmxciqwkrwtlvanpkfprksnyczysqkfjnrhwqhbmrcacwmpcxesxvdsfqwujxawjtcvgnrggkdqmudfipqwzplrqdudaozdyodkwpqgbehbhhtjxftvbwfpqmktkusqxrghbdzosfwzqmvjbcbjdxomkfnbaolbzrccjljmqhowemwxwmypsramxpbtkuvzuhpknnaxclkvcnicduasfvbwvwmcsalutznanvqjstqktmlobulkywmnimwlzhtewgbjexzbfwyzxoqhcgwmgayiekvccvokbonmwhsbyucmswxnmmgzyzqevmjbfjonutvbcrejizgjgxrmixdhbdxwgfdqtkyjplabxnliwwiciqyfcochapzajxyjvolyghfsjgyqmqszgyczhaqqtarjmewyulzngaybgobmiixkoabiwifasedrwltbjdjaqmproqaureqjajzhdtrgwcvhatjatqzpepuwdblksdszxdkntszbmxlbxbhpptdgfplrjtdmlncswakaiamthseblqkahghovsexpzepbgjifivrauuzyynzabydvgtmztaokatpzxgvohjmhwuljcdzyyshofyvzvrbfesectpbyglftmnmsjohftrjbdagayzpiqjbcvojesljykjmbtytopewepviahjipmlsgsurnhwblvrpuhfhpdhmvpiahaxzielzsdyvuuaavgkehbdlhtdtggquizhyycnvkxhgoczrnwqzniqmqeopkkshyftjxvghircdpwtwlawzebwnprytoaktdcffwtwqjuqptdcrjzuztzahuxefrkdznjdlblaxbvybgihkupqkiqxponynzirwdanukkuklahyzedvouemxgcifiyaaguujypnduphrjzgjcxfeolkkraetyczyvgcnspldqmnxdjrhjtknqlybgylqmsqtgpujwoqszgmicfojxuzfphhdpyfnffhuedgmlzggdmuajzssekpsgknyofgxhliikpmutyembubuitasvnwkkqdifdhuathlbaebvtqqwlrxqzkancmklljbeslajpdupsibwvksjlnjllekqjmcddjwlvqtccrtjhoovipwmqkeahwhsqjfyxbmqcnowxkedeilvgzizefwsmtxxvtloblmcfbbdikkngcogievxiqvkmrzbfipgjwabpnjllzbvlqshpcmpqbjgsebvkrahoqvymxexgqudlqiklqpfvkccfxxagkqwevcccqaforilhxjejryhvqwoglhjwphclprseupdhaiagwzjeabpgzbkyggbodvdlzunnnqlzadezxdwdrzwxckazkpqswlawgujaatqdxqhowbqxlsocujmocopinjqliyysldkvvjztetapeqzkcsqghiycsmytamkkanokqmvvwsifkgsmkqazypnwkcsriifsxgopvxplhnfkvfqzxvrosicjatomfiyuxyoyuyuktmsbnlfvztxhtuolagorwmroungfujfxiyotonohzrqqnxqyvswabcooeorenhhialgxzupsgigrnjhczimwgaeswjgemgljoywpemhtfkhfhwbwbmpirigzgfyjqvuhbyrupqngbirxalfveickmgecfjvoqnmaiskfhezswqfklkbdoyigcheqrdfufkxgsahglbrgdpldkgjyzegvzlnltzlnssmlpweshstfowrldpprjexzcekgcwzlmktbhzzsslfhwmtceowaslzabpmlmdbkpoidmpdzlljqugwngruauvcggtfgtlmkxorrlvsywyaawndoeaxrthjjkjbptejzjxxzkkfqocnpceabjnpjdxdsydnqvnvctalarwjwvrpqbayudmuliomihzkksmhbnxzgaigkuipbxvukcshswolkltqeblsgmbqrjaanhezhhfjxcnbefvbaa"
    ))
"""
此题解法：
* 利用切片然后翻转的方式进行比较，结果没有问题，但是效率比较低
* 还是利用双指针的方式，分别从左和从右取字符进行比较。
* 要注意的是，如果发现不相同，要分别处理左边跳一位和右边跳一位进行比较，如果有一种成功就继续比对下去，反之就要放弃
* 最好的就是指针配合切片方式

        a = s[::-1]
        
        if a == s:
            return True

        for i in range(len(s)):
            if s[i] != a[i]:
                temp_1 = s[:i] + s[i+1:]
                temp_2 = a[:i] + a[i+1:]
                return temp_1 == temp_1[::-1] or temp_2 == temp_2[::-1]

"""
